config/routes.rb
Rails.application.routes.draw do

  get 'blog/index'

  root 'welcome#index'

  get 'contact' => 'welcome#contact'

  get 'about' => 'welcome#about'

  get 'experience' => 'welcome#experience'

  get 'portfolio' => 'welcome#portfolio'

  get 'blog' => 'blog#index'

  get 'blog/post1' => 'blog#post1'

  get 'blog/post2' => 'blog#post2'

  get 'blog/post3' => 'blog#post3'

  get 'blog/post4' => 'blog#post4'
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog/index.html.erb
<div class="window">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2 blogstream">
        <h3><strong>Why you should teach kids how to code</strong></h3>
        <h4>February 19, 2016</h4>
        <p>During my time at Tech Talent South I volunteered to be a teaching assistant for their Kids Code Youth Camp for kids ages 8-13 every Monday afternoon. I was amazed at how excited these kids were to code even after a whole day at school under their belts...<a href="/blog/post4"> Read more</a></p>
      </div>
    </div>
    <div class="row">
    <div class="col-xs-8 col-sm-8 col-md-offset-2 blogstream">
      <h3><strong>How do I deal with this so-called "Impostor Syndrome"?</strong></h3>
      <h4>February 10, 2016</h4>
      <p>What is “impostor syndrome”? Does this mean I’m being fake? “Impostor syndrome can be defined as a collection of feelings of inadequacy that persist even in face of information that indicates that the opposite is true...<a href="/blog/post3"> Read more</a></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-8 col-sm-8 col-md-offset-2 blogstream">
        <h3><strong>I have a Q&A on Hypepotamus! What!?</strong></h3>
        <h4>December 30, 2015</h4>
        <p>During our first week of classes at Tech Talent South, our awesome community manager, Mandy Putnam, sent us a “social media round up spreadsheet” which basically included all of the newsletters, blogs, and tech accounts that we should follow...<a href="/blog/post2"> Read more</a></p>
      </div>
    </div>
	<div class="row">
    <div class="col-xs-8 col-sm-8 col-md-offset-2 blogstream">
      <h3><strong>What I learned at Tech Talent South in 8 weeks (besides coding, duh.)</strong></h3>
        <h4>December 4, 2015</h4>
        <p>When I joined Tech Talent South’s Fall 2015 cohort, I went in thinking that it would be just like another semester in college. I mean, I don’t like to brag, but I killed it in college and I’m a very quick learner.  I soon realized that this semester was twice as short and twice as hard...<a href="/blog/post1"> Read more</a></p>
      </div>
    </div>
  </div>
</div>

app/views/blog/post1.html.erb
<div class="window">
  <div class="container-fluid">
  	<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
      	<h3><strong>What I learned at Tech Talent South in 8 weeks (besides coding, duh.)</strong></h3>
      	<h4>December 4, 2015</h4>
      	<p>When I joined Tech Talent South’s Fall 2015 cohort, I went in thinking that it would be just like another semester in college. I mean, I don’t like to brag, but I killed it in college and I’m a very quick learner.  I soon realized that this semester was twice as short and twice as hard. At first, I thought two months was ample time to learn how to code, I mean everyone seems to be joining a coding boot camp these days, right? I’m certainly not the first one. I quickly realized that this was not the case.</p>
      	<p>As cliché as it sounds, coding, like most things in life, requires practice. And not just practicing-song-lyrics-in-the-shower-over-and-over-until-you-learn-the-song-practice, but dedicated and structured practice several hours a day if you are committed to learning in eight weeks. With this practice definitely comes dedication and commitment to learn. I could have easily gone to class everyday and followed move by move exactly what my awesome instructor Aaron did, but what would happen after class? Would I be able to just go home and be a coding ninja? Let me tell you, the answer is no.</p>
      	<p>These past eight weeks literally flew by. People say that time flies when you’re having fun, and I can truly say that these past 8 weeks were the highlight of my year and a great end to 2015. I’ve always been a good student, but sometimes you just get rusty and forget how to study. TTS taught me a newfound appreciation for detail, an infinite amount of patience, dedication and commitment to a craft (one of our guest speakers pointed out that coding is not a skill, but a craft), and learning how to code, duh. I also learned that switching to tea after 12pm for a caffeine boost makes you feel so much better than drinking coffee 24/7. I am learning how to code and I wouldn’t change this experience for anything else. Thank you TTS. </p>
        <p><a href="http://techtalentsouth.com/student-blog/what-i-learned-at-tech-talent-south-in-8-weeks-besides-coding/" target="_blank"> http://techtalentsouth.com/student-blog/what-i-learned-at-tech-talent-south-in-8-weeks-besides-coding/</a></p>
        <p>Originally posted on Tech Talent South website.</p>
        <p>
          <%= link_to "Back", blog_path %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/blog/post2.html.erb
<div class="window">
  <div class="container-fluid">
  	<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
      	<h3><strong>I have a Q&A on Hypepotamus! What!?</strong></h3>
      	<h4>December 30, 2015</h4>
      	<p>During our first week of classes at Tech Talent South, our awesome community manager, Mandy Putnam, sent us a “social media round up spreadsheet” which basically included all of the newsletters, blogs, and tech accounts that we should follow. The first one I followed and check regularly was Hypepotamus because they are the go-to source for hottest news, events, companies, people, and jobs in the Atlanta startup scene. I was amazed at how they connected companies with individuals and even took the chance to showcase students that were navigating their way through the Atlanta tech industry, which believe me, is no easy task. Imagine my surprise when I was chosen to be profiled on Hype at the end of my code immersion program!</p>
      	<p>Check out the Q&A below!</p>
      	<p><a href="http://www.hypepotamus.com/people/geraldine-galue/">http://www.hypepotamus.com/people/geraldine-galue/</a></p>
      	<p><i class="fa fa-quote-left fa-3x fa-pull-left"></i>Geraldine Galue is a talented tech lady with heart. When Galue isn’t creating her personal website, you can find her helping nonprofits build their brand and social media campaigns. This quick learner and lover of logic is looking for an internship or junior development position in a startup. She won’t be on the job market for long so snag her while you can.</p>
      	<p>- What program did you just complete?</p>
      	<p>I just completed Tech Talent South’s full-time Code Immersion Program.</p>
      	<p>- What did you build during your time in the course?</p>
      	<p>We built many apps during class, but I always went back home and worked on them to keep learning as much as possible. My first solo project was my personal website that I will eventually use to display my work. For my final class project, I built a web app that helps you organize your job search by keeping track of all the activity on your job applications without having to use messy spreadsheets or notes.</p>
      	<p>- What other past tech/creative projects have you worked on?</p>
      	<p>Besides my newfound love for coding, I also really enjoy writing and creating things. I work as a freelance writer and I also work with a couple of nonprofits helping them with their branding initiatives and social media campaigns, as well as producing their marketing and informational materials.</p>
      	<p>- What are your best technical or creative skills?</p>
      	<p>I have a business and logistics background so my brain works in numbers. I’m a quick learner and I love logic –basically anything that makes sense, like coding. I discovered that I really enjoy back-end development. I always thought I was more of a front-end development girl because I like things to look esthetically pleasing and I used to do basic HTML and CSS at my old job, but the more I learned about Rails, the more in love I fell with it.</p>
      	<p>- What’s next on your list to learn?</p>
      	<p>I’m always searching for something new to learn –that’s why I joined Tech Talent South. Right now I am definitely focusing on improving my current skills, but I would like to learn JavaScript and Angular. I’m old school and like to have books when I’m learning something new, so I just bought an intro to JavaScript book.</p>
        <p>- What tech/tools are essential to you?</p>
        <p>There are several that I use all the time: Github, Sublime, Photoshop, Stackoverflow, and any online tutorial or YouTube video that I get my hands on.</p>
        <p>- How do you stay informed & on top of emerging trends?</p>
        <p>During our first week of class our awesome community manager, Mandy, sent us a social media round spreadsheet which basically included all of the newsletters, blogs, and accounts that we should follow. I follow TechCrunch, Atlanta Tech Blogs, ATDC, ATV, Tech Drawl, and obviously Hypepotamus. I also attend Ruby meetups, which are great for networking.</p>
        <p>- What’s your ideal internship/job?</p>
        <p>As cliché as it sounds, my ideal internship or job would be one that exposes me to different types of projects, so that I can learn as much as possible. Ideally I would like to work at a startup because I really enjoy the culture and environment behind them. Also, a company that really values their employees and supports continuing education and development would be a plus.</p>
        <p>- Interested in startups?</p>
        <p>Yes, of course. The more I’ve immersed myself in the tech startup scene in ATL, I’ve realized that I would really like to work in one. Being involved in something that is being built from the ground up sounds challenging, yet exciting.</p>
        <p>- Post graduation plans?</p>
        <p>Currently, I am finishing up my portfolio and looking for an internship or full-time junior development position, ideally in a startup. However, I am still working on my personal projects in order to keep practicing and to gain more experience.</p>
        <p>- When are you available to start?</p>
        <p>As soon as possible!<i class="fa fa-quote-right fa-3x fa-pull-right"></i></p>
        <p>
      	 <%= link_to "Back", blog_path %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/blog/post3.html.erb
<div class="window">
  <div class="container-fluid">
  	<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
      	<h3><strong>How do I deal with this so-called "Impostor Syndrome"?</strong></h3>
      	<h4>February 10, 2016</h4>
        <p>What is “impostor syndrome”? Does this mean I’m being fake?</p>
        <p><i class="fa fa-quote-left fa-3x fa-pull-left"></i>“Impostor syndrome can be defined as a collection of feelings of inadequacy that persist even in face of information that indicates that the opposite is true. It is experienced internally as chronic self-doubt, and feelings of intellectual fraudulence. It is basically feeling that you are not really a successful, competent, and smart student, that you are only imposing as such.”**</p>
      	<p>Being a coding school graduate is an amazing feeling, but its also very nerve wrecking. Taking 3 months to learn a new skill from scratch is hard, but it speaks a lot about you –you’re not afraid to take on a challenge, you’re thirsty for knowledge, etc, etc, etc. It is no secret that the tech industry is HUGE in Atlanta, therefore its inevitable to feel at a disadvantage in comparison to someone with a 4-year CS college degree. It’s really easy to feel like you’re a fraud and that everyone will eventually find out.</p>
      	<p>A couple of months ago I went to an event hosted by Microsoft called Coddess, which aims to inspire female coders and help them achieve their professional goals through networking events, mentoring, and sharing their experiences. One lady asked the panel how we should deal with the “imposter syndrome” as a woman in tech. At the moment, I had just begun my program at Tech Talent South, so I didn’t quite understand what she was referring too. Now that I finished it, I completely understand what she was talking about. How do I compete with other people? What if people realize that I don’t know as much as they think?</p>
      	<p>I’ve asked several people in the industry this question and I think the general consensus is that when it comes to coding (and life in general, even though it sounds cliché), you never stop learning. There is always a new language, framework, library or something to learn. It just never stops. This is why I have decided to cease comparisons and focus on the value that I bring to the table, and not on attaining perfection. I am a person who aims high and is committed to giving my very best at every endeavor that I set my sights upon a.k.a. coding. </p>
        <h4>**Definition taken from: https://counseling.caltech.edu/general/InfoandResources/Impostor</h4>
        <p>
          <%= link_to "Back", blog_path %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/blog/post4.html.erb
<div class="window">
  <div class="container-fluid">
  	<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
      	<h3><strong>Why You Should Teach Your Kids How To Code</strong></h3>
      	<h4>February 19, 2016</h4>
        <p>During my time at Tech Talent South I volunteered to be a teaching assistant for their Kids Code Youth Camp for kids ages 8-13 every Monday afternoon. I was amazed at how excited these kids were to code even after a whole day at school under their belts. Although everything they learned was very basic, their talent and aptitude for learning certainly impressed me. They picked up these skills very quickly and they had no problem asking questions when they were unsure of something. This is the magical thing with children: they are not afraid. Adults have a tendency of being afraid to pick up new skills because they have other responsibilities and sometimes taking the time to learn something so time consuming as coding can be very daunting. </p>
      	<p>Yesterday, I volunteered to be a mentor at a hackathon for 9th and 10th graders who had been studying front-end web design and Ruby for 5 weeks. Their task was to build resources for Syrian refugee students in Georgia. I honestly did not know what I was signing myself up for. I thought I would just be walking around and giving ideas, but these kids had real ideas that developed into real web applications. The first place team developed web app that randomly generated vocabulary words translated using the Google Translate API. Other projects included an American idioms quiz, a website with information about the cities that they were being resettled to, a welcome page with messages translated from English to Arabic, and an American holiday’s quiz. Basically, these kids were amazing. I was helping them troubleshoot their Ruby code, giving them tips when using Bootstrap, and giving them pointers on how they could make their projects better. I never imagined that students in high school were already learning how to code! These high school kids definitely put me through the ringer –if you think 10-year olds weren’t afraid of asking me questions, well 15-year olds definitely asked me things that made my head hurt.  I came out of there exhausted, but extremely satisfied with myself. I definitely think that all school curriculums should include at least an intro to coding class at any grade level!</p>
        <p>
          <%= link_to "Back", blog_path %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<link href='https://fonts.googleapis.com/css?family=Puritan' rel='stylesheet' type='text/css'>

  <title>Geraldine Galue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "HOME", root_path %></li>
          <li><%= link_to "ABOUT", about_path %></li>
          <li><%= link_to "EXPERIENCE", experience_path %></li>
          <li><%= link_to "PORTFOLIO", portfolio_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "BLOG", blog_path %></li>
          <li><%= link_to "CONTACT", contact_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="header">
    <p id="center-it">
      <%= image_tag "logo.png", class: "logo", alt: "logo"%>
    </p>
  </div>
  <%= yield %>
  <div class="footer">
    <p id="center-it">Follow Me</p>
    <a href="mailto:geraldinegalue@gmail.com"><i class="fa fa-envelope-square fa-2x"></i></a>
    <a href="http://linkedin.com/in/ggalue" target="_blank"><i class="fa fa-linkedin-square fa-2x"></i></a>
    <a href="http://github.com/ggalue" target="_blank"><i class="fa fa-github-square fa-2x"></i>
    <a href="https://twitter.com/ggalue" target="_blank"><i class="fa fa-twitter-square fa-2x"></i>
    </div>
</body>
</html>

app/views/welcome/about.html.erb
<div class="window">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-4 col-md-4 test-class">
				<%= image_tag "me1.jpg", class: "img-responsive", id: "me", height: "400", width: "400" %>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-8" id="about">
				<h1 class="pg_title">About Me</h1>
				<p>My name is Geraldine Galue and I am a web developer based in Atlanta, GA. I was born and raised in Venezuela, but I moved to Georgia in 2008 for college. Although I majored in business and took courses in industrial engineering, the developing tech start-up scene in Atlanta had always caught my eye. In Fall 2015, I decided to take the plunge and joined Tech Talent South's full-time code immersion program and decided to learn how to code. I learned how to create dynamic web applications with Ruby on Rails, Gems, APIs, Databases, HTML, CSS & Javascript. Learning how to code in a short amount of time has certainly taught me a lot about myself and my capabilities. When I am not glued to my computer immersed in the wonderful world of coding, you can usually find me hanging out at tech meetups, restaurants around ATL, at the Beltline, or playing with my fur baby.</p>
			</div>
		</div>
	</div>
</div>

app/views/welcome/contact.html.erb
<div class="window">
  <div class="container-fluid">
  	<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
      	<h1>Have questions?</h1>
      	<h3>I have answers (maybe).</h3>
      	<h3>Click on the button below to send me an email and I will get back to you ASAP. Make sure you include your name, email and phone.</h3>
      	<%= link_to "Email Me", "mailto:geraldinegalue@gmail.com", class: "btn btn-lg btn-default" %>
      </div>
    </div>
	</div>
</div>

app/views/welcome/experience.html.erb
<div class="window">
	<div class="container-fluid">
		<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
				<h1>Do you need help with anything?</h1>
				<h3>Interested? Shoot me a message! These are my areas of expertise, but if you need something else, let me know!</h3>
				<p id="center-it">Website & Web App Development, Back-end Development, Content Writing, Resume Writing, Marketing & Branding, Event Management, Nonprofit Management</p>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-5 col-md-offset-1" id="services">
				<h1>Skills</h1>
				<ul class="fa-ul">
					<li><i class="fa-li fa fa-code-fork"></i>Ruby on Rails, JavaScript, HTML, CSS, HAML, Git, Github, APIs, jQuery, Wordpress, Drupal, SQLite, PostgreSQL, Bootstrap, Heroku</li>
					<li><i class="fa-li fa fa-laptop"></i>Microsoft Office Suite, Photoshop, Adobe Illustrator, Salesforce, Constant Contact, C-vent</li>
					<li><i class="fa-li fa fa-users"></i>Bilingual in Spanish and English, intermediate French</li>
					<li><i class="fa-li fa fa-user"></i>Multi-tasker, self-starter, team player, leader, writing & communications, positive attitude</li>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-5" id="services">
					<h1>Education</h1>
			<h3>Kennesaw State University</h3>
			<h4>August 2013</h4>
			<ul class="fa-ul">
				<li><i class="fa-li fa fa-graduation-cap"></i>BBA in International Business concentration in Management</li>
				<li><i class="fa-li fa fa-graduation-cap"></i>Minor in French and Francophone Studies</li>
				<li><i class="fa-li fa fa-graduation-cap"></i>Study Abroad in Sydney, Australia: Strategic and Financial Management for Entrepreneurial Businesses</li>
				<li><i class="fa-li fa fa-graduation-cap"></i>BS in Industrial Engineering coursework</li>
			</ul>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-5 col-md-offset-1" id="services">
			<h1>Experience</h1>
			<h3>Tech Talent South</h3>
			<p>Code Immersion Student</p>
			<h4>October 2015 – Present</h4>
			<ul class="fa-ul">
				<li><i class="fa-li fa fa-code"></i>Full-time code immersion program focused on learning and understanding: Ruby on Rails, Domain Modeling, HTTP and "RESTful" Design, HTML/CSS, Javascript and AJAX, APIs, Bootstrap, Git, Github, Ruby Gems</li>
				<li><i class="fa-li fa fa-code"></i>Teaching Assistant for Tech Talent South's Kids Code Program</li>
			</ul>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-5" id="services">
			<h3>SRMUN, Inc</h3>
			<p>Under Secretary-General</p>
			<h4>January 2015 – Present</h4>
			<ul class="fa-ul">
				<li><i class="fa-li fa fa-laptop"></i>Oversee the behind-the-scenes production of the conference</li>
				<li><i class="fa-li fa fa-laptop"></i>Create and execute detailed logistics plan for 30 staff members and 400+ college students and faculty</li>
				<li><i class="fa-li fa fa-laptop"></i>Manage the Conference Services office and team, and troubleshoot all hardware and software equipment</li>
				<li><i class="fa-li fa fa-laptop"></i>Produce marketing and informational materials</li>
				<li><i class="fa-li fa fa-laptop"></i>Help maintain the website and conference database</li>
			</ul>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-5 col-md-offset-1" id="services">
			<h3>Latin American Association</h3>
			<p>Development Coordinator</p>
			<h4>May 2012 – May 2013</h4>
			<ul class="fa-ul">
				<li><i class="fa-li fa fa-user"></i>Executed strategic development plan by coordinating logistics for fundraising events</li>
				<li><i class="fa-li fa fa-user"></i>Identified and established rapport with potential sponsors</li>
				<li><i class="fa-li fa fa-user"></i>Increased brand positioning efforts by implementing creative online marketing strategies, such as social media initiatives and email marketing campaigns</li>
				<li><i class="fa-li fa fa-user"></i>Maintained website using Joomla and custom HTML and CSS layout, and deployed and updated all marketing banners and promotions</li>
			</ul>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-5" id="services">
		&nbsp;&nbsp;
		<p>Volunteer Program Intern</p>
		<h4>January 2012 – May 2012</h4>
		<ul class="fa-ul">
			<li><i class="fa-li fa fa-users"></i>Identified potential volunteer opportunities</li>
			<li><i class="fa-li fa fa-users"></i>Recruited and oriented new volunteers, coordinated volunteers for projects, and managed the volunteer database through Salesforce</li>
			<li><i class="fa-li fa fa-users"></i>Successfully managed over 250 volunteers at Copa Latina and 300 volunteers at the Latino Youth Leadership Conference</li>
			<li><i class="fa-li fa fa-users"></i>Formed mutually beneficial partnerships with companies and educational institutions resulting in increased revenue and greater community involvement</li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-5 col-md-offset-1" id="services">
		<h3>Kennesaw State University</h3>
		<p>Spanish Tutor</p>
		<h4>January 2009 – February 2012</h4>
		<ul class="fa-ul">
			<li><i class="fa-li fa fa-pencil"></i>Tutored basic, intermediate and advanced Spanish grammar, composition, reading and linguistics</li>
			<li><i class="fa-li fa fa-pencil"></i>Designed promotional material for special events using Adobe Illustrator and Photoshop</li>
			<li><i class="fa-li fa fa-pencil"></i>Maintained the computer lab equipment and performed any other duties as assigned by lab coordinator</li>
		</ul>
	</div>
</div>
</div>
</div>

app/views/welcome/index.html.erb
<%= image_tag "index1.jpg", class: "img-responsive", id: "atl" %>

app/views/welcome/portfolio.html.erb
<div class="window">
	<div class="container-fluid">
		<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
      	<h3>Check out this short list of some of the things I've built. If you would like more samples, reach out to me!</h3>
      	<h1>Recipe Book</h1>
      	<%= image_tag "recipe.png", class: "img-responsive", id: "recipe" %>
				<h3>This is a recipe storage app that allows users to create and save recipes with ingredients and directions. The user can also edit and delete any recipe and browse other user's recipes. This app was built using Rails, Javascript, Bootstrap, AJAX, and HAML.</h3>
				<p id="center-it">
					<a href="https://github.com/ggalue/recipe-app" target="_blank">View Code</a>
				</p>
			</div>
		</div>
		<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
      	<h1>JobHunt</h1>
				<%= image_tag "jobhunt.png", class: "img-responsive", id: "jobhunt" %>
				<h3>JobHunt was my final project during my time at Tech Talent South. I got the idea after talking to my fellow classmates and realizing how difficult it is to organize your job search after graduation. JobHunt helps you organize your next job search by keeping track of all the activity on your job applications. With JobHunt, you simply search for jobs, save them, and take notes.</h3>
				<p id="center-it">
					<a href="https://github.com/ggalue/job_hunt_project" target="_blank">View Code</a>
				</p>
			</div>
		</div>
		<div class="row">
      <div class="col-xs-8 col-sm-8 col-md-offset-2">
      	<h1>To-Do List App</h1>
      	<%= image_tag "todolist.png", class: "img-responsive", id: "list" %>
				<h3>This is a simple app that allows users to create tasks and add todo items for each. The user can also edit and delete any task. This app was built using Rails, Javascript, Bootstrap, and AJAX. </h3>
				<p id="center-it">
					<a href="https://github.com/ggalue/todo_list" target="_blank">View Code</a>
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-8 col-sm-8 col-md-offset-2">
				<h1>Top5 App</h1>
				<%= image_tag "top5.png", class: "img-responsive", id: "list" %>
				<h3>Top5 allows users to populate their application with their favorite artists. They can also add their top songs for each artist and rate each one. This is a fun, functional application built with Rails, Bootstrap, and custom CSS.</h3>
				<p id="center-it">
					<a href="https://github.com/ggalue/top5_app" target="_blank">View Code</a>
				</p>
			</div>
		</div>
	</div>
</div>